// Auto-generated by OpenLane
module gelu_top(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input[31:0] s_axil_awaddr,
  input s_axil_awvalid,
  output s_axil_awready,
  input[31:0] s_axil_wdata,
  input[3:0] s_axil_wstrb,
  input s_axil_wvalid,
  output s_axil_wready,
  output[1:0] s_axil_bresp,
  output s_axil_bvalid,
  input s_axil_bready,
  input[31:0] s_axil_araddr,
  input s_axil_arvalid,
  output s_axil_arready,
  output[31:0] s_axil_rdata,
  output[1:0] s_axil_rresp,
  output s_axil_rvalid,
  input s_axil_rready,
  input[31:0] s_axis_tdata,
  input s_axis_tvalid,
  output s_axis_tready,
  input s_axis_tlast,
  input s_axis_tuser,
  output[31:0] m_axis_tdata,
  output m_axis_tvalid,
  input m_axis_tready,
  output m_axis_tlast,
  output m_axis_tuser
);
endmodule
