#include <iostream>
#include "Vadder_4bit.h"  // Generated by Verilator
#include "verilated.h"

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    Vadder_4bit* top = new Vadder_4bit; // Instantiate the module

    // Simple test: Add 5 + 3
    top->a = 5;
    top->b = 3;
    top->cin = 0;
    top->eval(); // Calculate logic

    std::cout << "Sum: " << (int)top->sum << " Carry: " << (int)top->cout << std::endl;

    delete top;
    return 0;
}