SIM 		= icarus
TOPLEVEL_LANG 	= verilog
VERILOG_SOURCES = $(PWD)/mac_correct.sv
TOPLEVEL 	= mac
MODULE 		= test_mac
COMPILE_ARGS       += -g2012

include $(shell python3 -m cocotb_tools.config --makefiles)/Makefile.sim
